### ISSUE TITLE
Close console login page when `auth.enabled` is false or close the login page.

### ISSUE THREAD

**Issue by KomachiSion** [alibaba/nacos#10153]
**Is your feature request related to a problem? Please describe.**

After `2.2.0.1` released, the `token.sceret.key` is a required value without default value. So It will make users **must** configure it even `auth.enabled` is false.

The most reason can't ignore `token.sceret.key` when `auth.enabled` is false is that the console has a login page which is strong depend the `token.sceret.key` to generate `accessToken`. 

So there is necessary to add a feature to close the login page when `auth.enabled` is false.

What's more, For other auth plugin, whether the login page should saved should be defined by plugins.

**Describe the solution you'd like**

- [x] Add `auth.enabled` status and `login.page.enabled` status from `/v1/console/server/state` API. #10203
- [x] The console ui judge  `login.page.enabled`, and stop redirect to login page when `login.page.enabled` is false. #10262 
- [x] Add announcement hint when `auth.enabled` is false to tell users the server has no auth. 
  - [x] Add announcement API such as  `/v1/console/server/announcement`. #10203 
  - [x] Show announcement in console pages. #10262 
- [x] Remove strong depend on `token.sceret.key` when `auth.enabled=false`, only keep stopping start when `auth.enabled=true` #10265
