### ISSUE TITLE
[Enhancement] Independent consistency module from naming module.

### ISSUE THREAD

**Issue by KomachiSion** [alibaba/nacos#3633]
**Is your feature request related to a problem? Please describe.**

Now, naming module implement two kinds of consistency packages : raft and distro.

But there are other module named consistency and it has implement raft by SOFAJraft.

So I want to replace naming's raft as SOFAJraft by using consistency module implementation and try to redesign distro and move it to consistency module.

**Describe the solution you'd like**

Replace naming's raft by consistency module.
Redesign and refactor naming's distro then move to consistency module.

**Additional context**
- [x] Replace naming's raft by consistency module. #3635
- [x] Redesign and discuss naming's distro. #3642
- [x] Refactor and move distro to consistency module. #3658

**Comment by horizonzy** [comment]
@KomachiSion  I will solve it
