### ISSUE TITLE
Add unit tests to package com.alibaba.nacos.client.config in nacos 2.0

### ISSUE THREAD

**Issue by shalk** [alibaba/nacos#5016]
## Issue Description

This is a sub-issue of [ISSUE #5011]
The package com.alibaba.nacos.client.config coverage rate is just 7%, Could you add more unit tests to nacos-client module?

## Anything else we need to know?

To-do list:

- [x]  Add unit tests for package com.alibaba.nacos.client.config.common #5030 
- [x]  Add unit tests for package com.alibaba.nacos.client.config.filter #5032 
- [x]  Add unit tests for package com.alibaba.nacos.client.config.http #5034 
- [x]  Add unit tests for package com.alibaba.nacos.client.config.impl #5103
- [x]  Add unit tests for package com.alibaba.nacos.client.config.listener #5036 
- [x]  Add unit tests for package com.alibaba.nacos.client.config.utils #5037 
- [x]  Add unit tests for package com.alibaba.nacos.client.*  other class

**Comment by shalk** [comment]
I will solve it

**Comment by shalk** [comment]
@KomachiSion  
should i split the issue again ?  or push one big pull request and work on it ?

**Comment by shalk** [comment]
done
