### ISSUE TITLE
Fix all of the unit tests in Nacos 2.x

### ISSUE THREAD

**Issue by realJackSun** [alibaba/nacos#5976]
sub-ISSUEs:
 - [x] Fix unit tests in nacos-naming #5982
 - [x] Fix unit tests in nacos-config #5983
 - [ ] Fix unit tests in nacos-client #5984
 - [x] Fix unit tests in nacos-core #5985
 - [x] Fix unit tests in nacos-address #5986
 - [x] Fix unit tests in nacos-common #5989
 - [x] Fix unit tests in nacos-consistency #5990
